### ISSUE TITLE
Hey, how do I implement this into a page that uses a webview.

### ISSUE THREAD

**Issue by JaydenDev** [NyaomiDEV/Glasstron#256]
How do I pass the blur to the webview?

**Comment by NyaomiDEV** [comment]
Glasstron only works on BrowserWindows. If you have a <webview> to style, you can use regular CSS to style it.

GNOME 42 by itself does not support any kind of blurring: Glasstron only really works OOB on KDE with X11. Efforts to support Glasstron-using applications are made by the guys over at BlurMyShell.
