### ISSUE TITLE
Can you provide binary *. node files in releases page

### ISSUE THREAD

**Issue by zhushenwudi** [NyaomiDEV/Glasstron#295]
**Is your feature request related to a problem? Please describe.**
Hello, I want to use this library on multiple platforms, including MacOS, Windows, Linux, and corresponding ARM64, ARM32, X86, X64 architecture
However, there are always errors in different platforms.It is hoped that the binary files that can be generated on Release can, the application can judge the use of files used by pre -processing scripts to achieve the purpose of increasing production speed

**Describe the solution you'd like**
This is the library I have already used
The author of this library wrote a Github actions to generate files auto
https://github.com/melchor629/node-flac-bindings

**Describe alternatives you've considered**
If you really don’t consider it, you can only use different computers to deal with these things.

**Additional context**
nothing

**Comment by NyaomiDEV** [comment]
Glasstron is impossible to compile on the platforms at my disposal (currently macOS) so I cannot provide you with .node binaries.

Do keep in mind that the native module only is needed on Windows and it is normal for other platforms to error out.
